# [build-system]
# requires = ["wheel", "setuptools"]
# build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
include = '''
(
    ^/ccl_app/.+[.]py
)
'''
exclude = '''
(
    __pycache__
  | ^/[.]
  | ^/doc
  | ^/env
)
'''
